version: "3"
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=./app.py
      - FLASK_DEBUG=development
    command: flask run
    volumes:
      - .:/code
  react-ui:
    image: sap19/disaster-pets-front-end
    ports:
      - "3000:3000"
