version: "3"
services:
  db:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=./app.py
      - FLASK_DEBUG=development
    command: flask run
    volumes:
      - .:/code
  web:
    image: sap19/disaster-pets-front-end
