"""empty message

Revision ID: ee035081ff18
Revises: 
Create Date: 2020-12-12 17:00:46.979976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee035081ff18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reporter', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('social', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'socialmedia', ['social'], ['id'])
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('social')
        batch_op.drop_column('reporter')
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
